<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Region;

class RegionSeeder extends Seeder
{
    public function run(): void
    {
        // Create Kabupaten Aceh Barat
        $acehBarat = Region::create([
            'type' => 'kabupaten',
            'name' => 'Aceh Barat',
            'code' => '1103',
            'parent_id' => null,
            'is_active' => true
        ]);

        // Data Kecamatan dan Desa
        $districts = [
            'Johan Pahlawan' => [
                'Blang Beurandang',
                'Drien Rampak',
                'Gampa',
                'Kampung Belakang',
                'Kampung Darat',
                'Kampung Pasir',
                'Kuta Padang',
                'Lapang',
                'Leuhan',
                'Padang Seurahet',
                'Panggong',
                'Pasar Aceh',
                'Rundeng',
                'Seuneubok',
                'Suak Nie',
                'Suak Raya',
                'Suak Ribee',
                'Suak Sigadeng',
                'Suak Indrapuri',
                'Ujong Baroh',
                'Ujung Kalak'
            ],
            'Samatiga' => [
                'Alue Raya',
                'Cot Amun',
                'Cot Darat',
                'Cot Lampise',
                'Cot Mesjid',
                'Cot Pluh',
                'Cot Seulamat',
                'Cot Seumeureung',
                'Deuah',
                'Gampong Cot',
                'Gampong Ladang',
                'Gampong Teungoh',
                'Keureuseng',
                'Krueng Tinggai',
                'Kuala Bubon',
                'Leubok',
                'Leuken',
                'Lhok Bubon',
                'Mesjid Baro',
                'Pange',
                'Paya Lumpat',
                'Pinem',
                'Pucok Leung',
                'Rangkileh',
                'Reusak',
                'Suak Geudeubang',
                'Suak Pandan',
                'Suak Pante Breuh',
                'Suak Seuke',
                'Suak Seumaseh',
                'Suak Timah',
                'Ujong Nga'
            ],
            'Bubon' => [
                'Alue Bakong',
                'Alue Lhok',
                'Beurawang',
                'Blang Sibeutong',
                'Cot Keumuneng',
                'Cot Lada',
                'Gunong Panah',
                'Kuala Pling',
                'Kuta Padang',
                'Layung',
                'Liceh',
                'Peulanteu',
                'Rambong',
                'Seumuleng',
                'Seuneubok Trap',
                'Suak Pangkat',
                'Ulee Blang'
            ],
            'Arongan Lambalek' => [
                'Alue Bagok',
                'Alue Batee',
                'Alue Sundak',
                'Arongan',
                'Cot Buloh',
                'Cot Juru Mudi',
                'Cot Kumbang',
                'Drien Rampak',
                'Gunong Pulo',
                'Karang Hampa',
                'Keub',
                'Kubu',
                'Pante Mutia',
                'Panton Bahagia',
                'Panton Makmur',
                'Peulanteu',
                'Peuribu',
                'Rimba Langgeh',
                'Seuneubok Lhong',
                'Seuneubok Teungoh',
                'Simpang Peut',
                'Suak Bidok',
                'Suak Ie Beuso',
                'Suak Keumudai',
                'Teupin Peuraho',
                'Ujong Beusa',
                'Ujong Simpang'
            ],
            'Woyla' => [
                'Alue Blang',
                'Alue Panyang',
                'Alue Sikaya',
                'Alue Sundak',
                'Aron Baroh',
                'Aron Tunong',
                'Bakat',
                'Blang Me',
                'Cot Keumundai',
                'Cot Lagan Bubon',
                'Cot Murong',
                'Cot Situah',
                'Darul Huda',
                'Drien Mangko',
                'Gempa Raya',
                'Glee Siblah',
                'Gunong Rambong',
                'Gunung Hampa',
                'Ie Itam Baroh',
                'Ie Itam Tunong',
                'Jawa',
                'Jawi',
                'Keuleumbah',
                'Kuala Bhee',
                'Lueng Buloh',
                'Lueng Jawa',
                'Lueng Tanoh Tho',
                'Lueng Teungku Yah',
                'Padang Jawa',
                'Panton',
                'Pasi Aceh',
                'Pasi Ara Kuala Batee',
                'Pasi Birah',
                'Pasi Lunak',
                'Pasi Pandan',
                'Paya Dua',
                'Paya Luah',
                'Pulo Ie',
                'Ranto Panyang',
                'Seumantok',
                'Suak Trieng',
                'Teumarom',
                'Tingkeum Panyang'
            ],
            'Woyla Barat' => [
                'Alue Keumuning',
                'Alue Leuhop',
                'Alue Permen',
                'Blang Cot Mameh',
                'Blang Cot Rubek',
                'Blang Luah Leuhop Mameh',
                'Cot Lagan Leuhop Mameh',
                'Cot Rambong',
                'Ie Sayang',
                'Karak',
                'Kulam Kaju',
                'Lhok Malee',
                'Lubuk Pasi Ara',
                'Lueng Baro',
                'Mon Pasong',
                'Napai',
                'Pasi Jeut',
                'Pasi Malee',
                'Pasi Mali',
                'Pasi Panyang',
                'Peuleukeung',
                'Simpang Keumaron',
                'Ule Pulo',
                'Ulei Pasi Ara'
            ],
            'Woyla Timur' => [
                'Alue Bilie',
                'Alue Empeuk',
                'Alue Kuyun',
                'Alue Meuganda',
                'Alue Seuralen',
                'Blang Dalam',
                'Blang Luah',
                'Blang Makmur',
                'Bukit Meugajah',
                'Cot Punti',
                'Gampong Baro',
                'Gampong Baro Woyla Timur',
                'Gunong Payang',
                'Keubeu Capang',
                'Lubuk Panyang',
                'Pasi Ara',
                'Pasi Janeng',
                'Paya Baro',
                'Paya Meugenderang',
                'Rambong',
                'Rambong Pinto',
                'Seuneubok Dalam',
                'Seuradeuk',
                'Tangkeh',
                'Teumiket Ranom',
                'Tuwi Empeuk'
            ],
            'Kaway XVI' => [
                'Alue Lhee',
                'Alue Lhok',
                'Alue On',
                'Alue Peudeung',
                'Alue Tampak',
                'Babah Meulaboh',
                'Beureugang',
                'Blang Dalam',
                'Blang Geunang',
                'Batu Jaya',
                'Drien Caleue',
                'Kampong Mesjid',
                'Keude Aron',
                'Keude Tanjong',
                'Keuramat',
                'Marek',
                'Meunasah Ara',
                'Meunasah Buloh',
                'Meunasah Gantung',
                'Meunasah Rambot',
                'Meunasah Rayeuk',
                'Meunuang Tanjong',
                'Muko',
                'Padang Mancang',
                'Padang Sikabu',
                'Palimbungan',
                'Pasi Ara',
                'Pasi Jambu',
                'Pasi Jeumpa',
                'Pasi Kumbang',
                'Pasi Meugat',
                'Pasi Teungoh',
                'Peunia',
                'Pucok Pungkie',
                'Pungkie',
                'Putim',
                'Puuk',
                'Sawang Teubei',
                'Simpang',
                'Tanjong Bungong',
                'Tanjong Meulaboh',
                'Teladan',
                'Teupin Panah',
                'Tumpok Ladang'
            ],
            'Meureubo' => [
                'Balee',
                'Bukit Jaya',
                'Buloh',
                'Gunong Kleng',
                'Langung',
                'Mesjid Tuha',
                'Meureubo',
                'Pasi Aceh Baroh',
                'Pasi Aceh Tunong',
                'Pasi Mesjid',
                'Pasi Pinang',
                'Paya Baro Ranto Panyang',
                'Paya Peunaga',
                'Peunaga Cut Ujong',
                'Peunaga Pasi',
                'Peunaga Rayeuk',
                'Pucok Reudeup',
                'Pulo Teungoh Ranto Panyang',
                'Ranto Panyang Barat',
                'Ranto Panyang Timur',
                'Ranub Dong',
                'Reudeup',
                'Sumber Batu',
                'Ujong Drien',
                'Ujong Tanjung',
                'Ujong Tanoh Darat'
            ],
            'Pante Ceureumen' => [
                'Alue Keumang',
                'Babah Iseung',
                'Babah Krueng Tep Lep',
                'Babah Lueng',
                'Berdikari',
                'Canggai',
                'Gunong Tarok',
                'Jambak',
                'Keutambang',
                'Keude Suak Awe',
                'Krueng Beukah',
                'Lango',
                'Lawet',
                'Lhok Guci',
                'Lhok Sari',
                'Manjeng',
                'Meunaung Kinco',
                'Pante Ceureumen',
                'Pulo Teungoh Manyang',
                'Sawang Rambot',
                'Seumantok',
                'Seumara',
                'Sikundo',
                'Suak Awe',
                'Tegal Sari'
            ],
            'Panton Reu' => [
                'Antong',
                'Babah Krueng Manggie',
                'Baro Paya',
                'Blang Balee',
                'Blang Teungoh',
                'Cot Manggie',
                'Gampong Baro',
                'Gunung Mata Ie',
                'Kuala Manye',
                'Lek-Lek',
                'Manggie',
                'Meutulang',
                'Mugo Cut',
                'Mugo Rayeuk',
                'Paya Baro Meuko',
                'Sibintang',
                'Tamping',
                'Tuwi Buya',
                'Ujong Raja'
            ],
            'Sungai Mas' => [
                'Drien Sibak',
                'Gaseu',
                'Geudong',
                'Gleung',
                'Gunong Buloh',
                'Kajeung',
                'Lancong',
                'Lubok Beutong',
                'Lueng Baro',
                'Pungki',
                'Ramitie',
                'Sakuy',
                'Sarah Perlak',
                'Sipot',
                'Tanoh Mirah',
                'Tungkop',
                'Tutut',
                'Tuwi Saya'
            ]
        ];

        foreach ($districts as $districtName => $villages) {
            // Create district
            $district = Region::create([
                'type' => 'kecamatan',
                'name' => $districtName,
                'parent_id' => $acehBarat->id,
                'is_active' => true
            ]);

            // Create villages for this district
            foreach ($villages as $villageName) {
                Region::create([
                    'type' => 'desa',
                    'name' => $villageName,
                    'parent_id' => $district->id,
                    'is_active' => true
                ]);
            }
        }
    }
}
